services:
  bot:
    image: ghcr.io/floshv1/floshy_bot:latest
    container_name: floshy_bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      LOG_LEVEL: INFO
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - uv-cache:/root/.cache/uv
    networks:
      - bot-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  bot-network:
    driver: bridge

volumes:
  uv-cache:
    driver: local